---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-marbles-org2
  namespace: hyperledger
  labels:
    app: chaincode-marbles-org2
spec:
  selector:
    matchLabels:
      app: chaincode-marbles-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-marbles-org2
    spec:
      containers:
        - image: ss75710541/chaincode-marbles:1.0
          name: chaincode-marbles-org2
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_CCID
              value: "marbles:1b05e4523b4dd26ffbcd884a856eb58fab6f76591e7c5b00825fe2382e9ed822"
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
